[[LicenseSpring]]
arch = "i686"
git-tree-sha1 = "0a1b1503c8e3c0e44cc4726c6cd307eeee2c4b87"
os = "windows"

    [[LicenseSpring.download]]
    sha256 = "be607b10a4f2b6fceb8de3c9fefee1d6846d4b9286867a26edbfb2e8f70a40ac"
    url = "https://github.com/juliacomputing/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.4.0+0/LicenseSpring.v7.4.0.i686-w64-mingw32.tar.gz"
[[LicenseSpring]]
arch = "x86_64"
git-tree-sha1 = "75f91280ed934e5e1cae968970cf5850ae7b0811"
os = "windows"

    [[LicenseSpring.download]]
    sha256 = "faab61cbf4f4186319f84adb3bfb0f1e94a93dedfe79d677831207b4dd49af86"
    url = "https://github.com/juliacomputing/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.4.0+0/LicenseSpring.v7.4.0.x86_64-w64-mingw32.tar.gz"
