[[LicenseSpring]]
arch = "aarch64"
git-tree-sha1 = "52f91d3574e2442cbbdc99b369975faf6e4fd943"
os = "macos"

    [[LicenseSpring.download]]
    sha256 = "428b97ba3477bea2e5b3e65be206d948545a3baab773e8f7a38ecdf5cc91b68a"
    url = "https://github.com/PumasAI/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.16.0+0/LicenseSpring.v7.16.0.aarch64-apple-darwin.tar.gz"
[[LicenseSpring]]
arch = "i686"
git-tree-sha1 = "49376490f2ee72acce626ab679bd5858377e7960"
os = "windows"

    [[LicenseSpring.download]]
    sha256 = "874fd14650e597c10a10d2bf19e5e027f851ab40e6100204c846382a44078ccb"
    url = "https://github.com/PumasAI/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.16.0+0/LicenseSpring.v7.16.0.i686-w64-mingw32.tar.gz"
[[LicenseSpring]]
arch = "x86_64"
git-tree-sha1 = "72d03b372a8a475ae27cead6ae25597e47108ea7"
os = "macos"

    [[LicenseSpring.download]]
    sha256 = "8acf99db79008d40284f8fe6466fd1745a1d77414571d95e76174e5f242e8088"
    url = "https://github.com/PumasAI/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.16.0+0/LicenseSpring.v7.16.0.x86_64-apple-darwin.tar.gz"
[[LicenseSpring]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a8cd5a1238eae8511a1156e8b1787428a29b707"
libc = "glibc"
os = "linux"

    [[LicenseSpring.download]]
    sha256 = "266959cb76c9059484e97db5d76945273cd5b8d04576ad07ae2f4f116c3458ce"
    url = "https://github.com/PumasAI/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.16.0+0/LicenseSpring.v7.16.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LicenseSpring]]
arch = "x86_64"
git-tree-sha1 = "3a014f35d9a73bfead3390e8258d81e5208efd3f"
os = "windows"

    [[LicenseSpring.download]]
    sha256 = "5f927211078bb56a0c283b8e04782195c9853f04a7d77c036494095511b58e09"
    url = "https://github.com/PumasAI/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.16.0+0/LicenseSpring.v7.16.0.x86_64-w64-mingw32.tar.gz"
