[[LicenseSpring]]
arch = "aarch64"
git-tree-sha1 = "9982169fdf00c0caa31fa77cda8c3d847a2b0eb7"
os = "macos"

    [[LicenseSpring.download]]
    sha256 = "b5953014560d79d707a7854f1a8878f15f1ba9f3b2ed27115d4fe5ae465500c1"
    url = "https://github.com/PumasAI/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.16.0+0/LicenseSpring.v7.16.0.aarch64-apple-darwin.tar.gz"
[[LicenseSpring]]
arch = "i686"
git-tree-sha1 = "92b88f613024d6cde4482c7d420245202fa3c1a0"
os = "windows"

    [[LicenseSpring.download]]
    sha256 = "a1d033e949c12bcf923b87d0f050d2f416ba4d77a0e253e24a44567552183f6b"
    url = "https://github.com/PumasAI/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.16.0+0/LicenseSpring.v7.16.0.i686-w64-mingw32.tar.gz"
[[LicenseSpring]]
arch = "x86_64"
git-tree-sha1 = "b372b7ad4e96191801f4dad369218599895c6b94"
os = "macos"

    [[LicenseSpring.download]]
    sha256 = "03b56f9b6cb5a3ff847a0e44c489df29bde5153bd5083d087a3ce472d93a61ff"
    url = "https://github.com/PumasAI/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.16.0+0/LicenseSpring.v7.16.0.x86_64-apple-darwin.tar.gz"
[[LicenseSpring]]
arch = "x86_64"
git-tree-sha1 = "b72936ed23dd0bffe70548de4280b9218d8e632b"
os = "windows"

    [[LicenseSpring.download]]
    sha256 = "0cc44fb17a2a15826c29176fa12cad7909c6e21bf8a56fcb1ca9d5a9fe23f2a3"
    url = "https://github.com/PumasAI/LicenseSpring_jll.jl/releases/download/LicenseSpring-v7.16.0+0/LicenseSpring.v7.16.0.x86_64-w64-mingw32.tar.gz"
